### ISSUE TITLE
OpenCV issue : No OpenGL support(Library built without OpenGL support) in cvNamedWIndows ,file .\ \\opencv\modules\highgui\src\window_w32.cpp line 746

### ISSUE THREAD

**Issue by Reena24** [MasteringOpenCV/code#25]
I am trying the code for Markerless AR in Visual Studio 2008 with OpenCV 2.4.4   in Windows 7but i come across this error. I have configured everything needed for the code. I downloaded Opencv 2.4.4.exe from sourceforge and enabled OpenGL using cmake but it still shows error.
It shows the same error for the function:
cv::namedWindow(windowName, cv::WINDOW_OPENGL);
 cv::setOpenGlContext(windowName);
 cv::setOpenGlDrawCallback(windowName, ARDrawingContextDrawCallback, this);
I use the Intel graphics(Generic PnP Monitor on Intel HD Graphics 4000 Driver version   10.18.10.3345)
I also tried the same code in Nvidia system which showed the same error.
I would really like it if i could a stepwise instruction on how to setup the markerless ar project and solve the OpenGL support problem.
I fell its a code error
I have a deadline of 2 days to complete the code I could use all the help i can get .
Please Help!!!
![1](https://f.cloud.github.com/assets/6601115/2095115/66aecd3c-8edb-11e3-9e42-a15276afc534.png)

**Comment by chenxinhua** [comment]
how to solve the problem no opengl support(library was built without opengl support)

**Comment by ekhvedchenya-daqri** [comment]
Unfortunately, OpenGL support is not supported on MAC. As far as I know, OpenCV dev. team does not have plans to implement OpenGL support for this platform.

**Comment by BloodAxe** [comment]
Unfortunately, OpenGL support is not supported on MAC. As far as I know,
OpenCV dev. team does not have plans to implement OpenGL support for this
platform.

2016-06-30 11:03 GMT+03:00 chenxinhua notifications@github.com:

**Comment by coryl** [comment]
How to build with MAC and QT5:
http://programmingopencvopengletc.blogspot.ca/2014/11/opengl-support-for-opencv-249-in-mac-os.html

**Comment by gohyz** [comment]
I also met this problem. 
Finally I found that it is because I added another opencv to the Path environment.
how can you know this. if you use MSVC, you can check the Output TAB of the MSVC IDE.
in the Output TAB you can see the loading module as show in the below. 
Hope this can help the guys who met the same problem.

///////////////////////////////////////
'markerless_ar_demo.exe' (Win32): Loaded 'E:\00_SfM\Mastering_OpenCV_Code\Chapter3_MarkerlessAR\build\src\Debug\markerless_ar_demo.exe'. Symbols loaded.
'markerless_ar_demo.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'markerless_ar_demo.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'markerless_ar_demo.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'markerless_ar_demo.exe' (Win32): Loaded 'C:\Windows\System32\opengl32.dll'. Cannot find or open the PDB file.
'markerless_ar_demo.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
'markerless_ar_demo.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Cannot find or open the PDB file.
'markerless_ar_demo.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
'markerless_ar_demo.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'markerless_ar_demo.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Cannot find or open the PDB file.
'markerless_ar_demo.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Cannot find or open the PDB file.
'markerless_ar_demo.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Cannot find or open the PDB file.
'markerless_ar_demo.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Cannot find or open the PDB file.
'markerless_ar_demo.exe' (Win32): Loaded 'C:\Windows\System32\ddraw.dll'. Cannot find or open the PDB file.
'markerless_ar_demo.exe' (Win32): Loaded 'C:\Windows\System32\dciman32.dll'. Cannot find or open the PDB file.
'markerless_ar_demo.exe' (Win32): Loaded 'E:\00_SfM\Mastering_OpenCV_Code\Chapter3_MarkerlessAR\build\src\Debug\opencv_calib3d2413d.dll'. Symbols loaded.
'markerless_ar_demo.exe' (Win32): Loaded 'E:\00_SfM\Mastering_OpenCV_Code\Chapter3_MarkerlessAR\build\src\Debug\opencv_highgui2413d.dll'. Symbols loaded.
'markerless_ar_demo.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Cannot find or open the PDB file.
