### ISSUE TITLE
Chapter 6 - Chapter 7 Disconnect

### ISSUE THREAD

**Issue by akapusta** [MasteringOpenCV/code#51]
There seems to be a disconnect between chapters 6 and 7. Chapter 6 describes a process for tracking and fitting a deformable model in an image. Chapter 7 describes a process for extracting a pose for a 3D model from an image. However, there is no description on how to convert the deformable model into a 3D model. Jason's has published work which uses deformable models to extract a pose (position and orientation) from images, but that process is lacking from the book and that functionality is missing from the code. Might it be possible for that functionality to be added?

**Comment by shervinemami** [comment]
Yes it's true, in fact each chapter is fairly disconnected because they are all separate projects from different authors, so that someone can jump straight into any chapter of the book and create that project without necessarily working on other chapters of the book.

About Jason's code, it's true that he published a pose estimation library called FaceTracker, but the book is about learning how things work and how to solve problems, so he wanted to write that chapter about pose extraction using the basic concepts from scratch and not be too complex. Whereas his published code is more complicated since users aren't trying to learn the internals.
